name: flutter_retrofit_bloc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  retrofit: any
  json_annotation: any  
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: any
  build_runner: ^2.0.4
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
